import { StyleSheet } from "react-native";
export const Mstyle = StyleSheet.create({
    container:{
        margin: 0,
        padding: 0,
        paddingTop: 20,
        flex: 1,
        alignItems: 'center',
    },
    subject:{
      width: 360,
      backgroundColor: '#FDFDFD',
      height: 80,
      borderColor: '#0F6CBF',
      borderWidth: 1,
      borderLeftWidth: 5,
      borderRadius: 10,
      paddingLeft: 20,
      borderTopLeftRadius: 0,
      borderBottomLeftRadius: 0,
      marginTop: 20,
      boxShadow: '0px 5px 6px rgba(0, 0, 0, 0.1)',
      elevation: 5,
      justifyContent: 'center',
      shadowRadius: 20,
    },
    subjectDataTxt:{
      fontSize: 14,
      width: 180,
      textAlign: 'baseline',
      fontFamily: 'noto-sans'
    },
    subjectContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center', 
    },
    attendance: {
        marginRight: 40,
    },
    subjectInfo:{
        width: '100%',
        height: 50,
        justifyContent: 'center',
        paddingHorizontal: 20,
        flexWrap: 'wrap',
    },
    modalData:{
        flex: 1,
        paddingHorizontal: 5,
    },
    subjectName:{
        fontSize: 18,
        fontFamily: 'noto-sans',
        fontWeight: '600',
        textTransform: 'uppercase',    
    },
    header:{
        width: '100%',
        flexDirection: 'row',    
        justifyContent: 'space-evenly',    
        marginVertical: 10,
    },
    headerText:{
        fontSize: 16,
        fontFamily: 'noto-sans',
        textTransform: 'uppercase',
        fontWeight: 'light',
        width: '53%',
        textAlign: 'center',
    },
    dateItem:{
        flexDirection: 'row',
        width: '100%',
        height: 50,
        borderTopWidth: 0.5,
        justifyContent: 'space-evenly',
        alignItems: 'center'
    },
    itemText:{
        fontSize: 14,
        width: '53%',
        textAlign: 'center',
    },
    changeMonthBtn: {
        height: 30,
        marginVertical: 5,
        alignItems: 'center',
        backgroundColor: '#0F6CBF',
        borderRadius: 5,
        justifyContent: 'center',
    },
    changeMonthBtnText: {
        color: '#FFF',
        fontSize: 16,
        textAlign: 'center',
        fontWeight: '600',
        textTransform: 'uppercase',
    },
    closeBtn: {
        marginVertical: 20,
        alignItems: 'center',
        height: 30,
        backgroundColor: '#D9534F',
        borderRadius: 5,
        justifyContent: 'center',
    },
    closeBtnText: {
        color: '#FFF',
        fontSize: 16,
        textAlign: 'center',
        fontWeight: '600',
        textTransform: 'uppercase',
    },
});